version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "elazamey"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "elazamey"
    labels:
      - "dependencies"
      - "dashboard"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "actions"
