// Audit inventory snapshot, NOT a claim that 200 features are operational.
// Corresponds to docs/nexa-capability-matrix.csv (2026-09-20).
export const CATALOG_ROWS = Object.freeze([
  Object.freeze(["A001", "Agentic Planning", "P", "R4"]),
  Object.freeze(["A002", "ReAct", "P", "R4"]),
  Object.freeze(["A003", "Reflection", "M", "R4"]),
  Object.freeze(["A004", "Self-Critique", "P", "R4"]),
  Object.freeze(["A005", "Self-Verification", "P", "R4"]),
  Object.freeze(["A006", "Self-Correction", "P", "R4"]),
  Object.freeze(["A007", "Tree of Thoughts", "N", "R7"]),
  Object.freeze(["A008", "Graph of Thoughts", "N", "R7"]),
  Object.freeze(["A009", "Chain of Thought", "P", "R4"]),
  Object.freeze(["A010", "Least-to-Most Reasoning", "N", "R4"]),
  Object.freeze(["A011", "Self-Consistency", "N", "R7"]),
  Object.freeze(["A012", "Tool Calling", "P", "R1"]),
  Object.freeze(["A013", "Function Calling", "P", "R3"]),
  Object.freeze(["A014", "MCP", "M", "R3"]),
  Object.freeze(["A015", "Tool Routing", "P", "R3"]),
  Object.freeze(["A016", "Model Routing", "P", "R3"]),
  Object.freeze(["A017", "Provider Routing", "P", "R3"]),
  Object.freeze(["A018", "Mixture of Experts", "N", "R8"]),
  Object.freeze(["A019", "Ensemble AI", "N", "R7"]),
  Object.freeze(["A020", "Model Cascading", "N", "R3"]),
  Object.freeze(["A021", "Fallback Models", "P", "R3"]),
  Object.freeze(["A022", "Semantic Cache", "N", "R3"]),
  Object.freeze(["A023", "Response Cache", "N", "R3"]),
  Object.freeze(["A024", "Prompt Cache", "N", "R3"]),
  Object.freeze(["A025", "KV Cache", "D", "R8"]),
  Object.freeze(["A026", "Working Memory", "P", "R2"]),
  Object.freeze(["A027", "Episodic Memory", "P", "R2"]),
  Object.freeze(["A028", "Semantic Memory", "P", "R2"]),
  Object.freeze(["A029", "Procedural Memory", "P", "R4"]),
  Object.freeze(["A030", "Long-Term Memory", "P", "R2"]),
  Object.freeze(["A031", "Short-Term Memory", "P", "R2"]),
  Object.freeze(["A032", "Memory Consolidation", "P", "R2"]),
  Object.freeze(["A033", "Memory Decay", "P", "R2"]),
  Object.freeze(["A034", "Memory Retrieval", "P", "R2"]),
  Object.freeze(["A035", "Context Compression", "N", "R3"]),
  Object.freeze(["A036", "Context Summarization", "N", "R3"]),
  Object.freeze(["A037", "Context Management", "P", "R3"]),
  Object.freeze(["A038", "Prompt Engineering", "P", "R3"]),
  Object.freeze(["A039", "Prompt Chaining", "P", "R4"]),
  Object.freeze(["A040", "Dynamic Prompting", "P", "R3"]),
  Object.freeze(["A041", "Prompt Optimization", "N", "R6"]),
  Object.freeze(["A042", "Structured Outputs", "P", "R3"]),
  Object.freeze(["A043", "JSON Schema Validation", "P", "R1"]),
  Object.freeze(["A044", "Guardrails", "P", "R1"]),
  Object.freeze(["A045", "Policy Engine", "M", "R1"]),
  Object.freeze(["A046", "Authorization Engine", "P", "R1"]),
  Object.freeze(["A047", "Capability System", "M", "R1"]),
  Object.freeze(["A048", "Capability Tokens", "M", "R1"]),
  Object.freeze(["A049", "RBAC", "P", "R1"]),
  Object.freeze(["A050", "ABAC", "P", "R1"]),
  Object.freeze(["A051", "ACL", "P", "R1"]),
  Object.freeze(["A052", "Zero Trust", "P", "R1"]),
  Object.freeze(["A053", "Sandboxing", "D", "R1"]),
  Object.freeze(["A054", "Secure Execution", "P", "R1"]),
  Object.freeze(["A055", "Human-in-the-Loop", "P", "R1"]),
  Object.freeze(["A056", "Human-on-the-Loop", "P", "R2"]),
  Object.freeze(["A057", "Approval Gates", "P", "R1"]),
  Object.freeze(["A058", "Execution Gateway", "P", "R1"]),
  Object.freeze(["A059", "Action Verification", "P", "R1"]),
  Object.freeze(["A060", "Provenance Tracking", "P", "R2"]),
  Object.freeze(["A061", "Evidence Ledger", "P", "R2"]),
  Object.freeze(["A062", "Audit Trail", "P", "R2"]),
  Object.freeze(["A063", "Cryptographic Signing", "M", "R1"]),
  Object.freeze(["A064", "Hash Chaining", "M", "R2"]),
  Object.freeze(["A065", "Replay Protection", "P", "R0"]),
  Object.freeze(["A066", "Idempotency", "N", "R2"]),
  Object.freeze(["A067", "Transaction Manager", "P", "R0"]),
  Object.freeze(["A068", "Rollback System", "P", "R0"]),
  Object.freeze(["A069", "Checkpointing", "P", "R2"]),
  Object.freeze(["A070", "State Machine", "M", "R2"]),
  Object.freeze(["A071", "Event Sourcing", "P", "R2"]),
  Object.freeze(["A072", "Event Bus", "P", "R2"]),
  Object.freeze(["A073", "Message Queue", "P", "R2"]),
  Object.freeze(["A074", "Task Scheduler", "P", "R2"]),
  Object.freeze(["A075", "Priority Queue", "P", "R2"]),
  Object.freeze(["A076", "Retry Engine", "P", "R2"]),
  Object.freeze(["A077", "Circuit Breaker", "M", "R2"]),
  Object.freeze(["A078", "Rate Limiting", "P", "R1"]),
  Object.freeze(["A079", "Budget Controller", "P", "R3"]),
  Object.freeze(["A080", "Token Budgeting", "P", "R3"]),
  Object.freeze(["A081", "Resource Governor", "P", "R1"]),
  Object.freeze(["A082", "Health Monitoring", "M", "R2"]),
  Object.freeze(["A083", "Observability", "P", "R2"]),
  Object.freeze(["A084", "Distributed Tracing", "N", "R2"]),
  Object.freeze(["A085", "Metrics Engine", "P", "R2"]),
  Object.freeze(["A086", "Anomaly Detection", "P", "R6"]),
  Object.freeze(["A087", "Drift Detection", "N", "R6"]),
  Object.freeze(["A088", "Evaluation Engine", "M", "R5"]),
  Object.freeze(["A089", "Benchmarking", "P", "R5"]),
  Object.freeze(["A090", "Red Teaming", "M", "R1"]),
  Object.freeze(["A091", "Adversarial Testing", "M", "R0"]),
  Object.freeze(["A092", "Prompt Injection Defense", "P", "R1"]),
  Object.freeze(["A093", "Tool Poisoning Defense", "P", "R1"]),
  Object.freeze(["A094", "Output Sanitization", "P", "R1"]),
  Object.freeze(["A095", "Secret Detection", "P", "R1"]),
  Object.freeze(["A096", "PII Detection", "P", "R1"]),
  Object.freeze(["A097", "Data Loss Prevention", "P", "R1"]),
  Object.freeze(["A098", "Digital Twin", "P", "R7"]),
  Object.freeze(["A099", "Simulation Engine", "D", "R7"]),
  Object.freeze(["A100", "World Model", "P", "R4"]),
  Object.freeze(["B001", "Neuro-Symbolic AI", "D", "R7"]),
  Object.freeze(["B002", "Knowledge Graph", "P", "R5"]),
  Object.freeze(["B003", "Ontology Engine", "N", "R5"]),
  Object.freeze(["B004", "Semantic Reasoner", "N", "R5"]),
  Object.freeze(["B005", "Rule Engine", "P", "R5"]),
  Object.freeze(["B006", "Constraint Solver", "D", "R5"]),
  Object.freeze(["B007", "SAT Solver", "D", "R5"]),
  Object.freeze(["B008", "SMT Solver", "D", "R5"]),
  Object.freeze(["B009", "Probabilistic Reasoning", "P", "R6"]),
  Object.freeze(["B010", "Bayesian Network", "N", "R8"]),
  Object.freeze(["B011", "Causal Inference", "D", "R8"]),
  Object.freeze(["B012", "Causal Graph", "P", "R8"]),
  Object.freeze(["B013", "Temporal Reasoning", "P", "R5"]),
  Object.freeze(["B014", "Spatial Reasoning", "N", "R8"]),
  Object.freeze(["B015", "Counterfactual Reasoning", "D", "R8"]),
  Object.freeze(["B016", "Abductive Reasoning", "P", "R5"]),
  Object.freeze(["B017", "Inductive Reasoning", "P", "R6"]),
  Object.freeze(["B018", "Deductive Reasoning", "P", "R5"]),
  Object.freeze(["B019", "Analogical Reasoning", "P", "R4"]),
  Object.freeze(["B020", "Fuzzy Logic", "N", "R8"]),
  Object.freeze(["B021", "Formal Verification", "D", "R5"]),
  Object.freeze(["B022", "Model Checking", "N", "R5"]),
  Object.freeze(["B023", "Theorem Proving", "N", "R8"]),
  Object.freeze(["B024", "Symbolic Execution", "N", "R5"]),
  Object.freeze(["B025", "Static Analysis", "M", "R5"]),
  Object.freeze(["B026", "Dynamic Analysis", "P", "R5"]),
  Object.freeze(["B027", "Program Synthesis", "D", "R8"]),
  Object.freeze(["B028", "Code Generation", "P", "R4"]),
  Object.freeze(["B029", "Code Repair", "P", "R4"]),
  Object.freeze(["B030", "Code Refactoring", "P", "R5"]),
  Object.freeze(["B031", "Code Review Agent", "P", "R4"]),
  Object.freeze(["B032", "Test Generation", "P", "R5"]),
  Object.freeze(["B033", "Test Selection", "N", "R5"]),
  Object.freeze(["B034", "Mutation Testing", "N", "R5"]),
  Object.freeze(["B035", "Fuzzing", "P", "R5"]),
  Object.freeze(["B036", "Property-Based Testing", "P", "R5"]),
  Object.freeze(["B037", "Regression Detection", "M", "R5"]),
  Object.freeze(["B038", "Dependency Analysis", "P", "R5"]),
  Object.freeze(["B039", "Supply Chain Security", "P", "R1"]),
  Object.freeze(["B040", "SBOM Engine", "N", "R5"]),
  Object.freeze(["B041", "Vulnerability Scanner", "N", "R5"]),
  Object.freeze(["B042", "Secrets Vault", "P", "R1"]),
  Object.freeze(["B043", "Key Management", "P", "R1"]),
  Object.freeze(["B044", "Identity Federation", "P", "R1"]),
  Object.freeze(["B045", "Attestation", "P", "R8"]),
  Object.freeze(["B046", "Trusted Execution", "N", "R8"]),
  Object.freeze(["B047", "Secure Enclave", "N", "R8"]),
  Object.freeze(["B048", "Confidential Computing", "N", "R8"]),
  Object.freeze(["B049", "Differential Privacy", "N", "R8"]),
  Object.freeze(["B050", "Federated Learning", "D", "R8"]),
  Object.freeze(["B051", "Continual Learning", "P", "R6"]),
  Object.freeze(["B052", "Online Learning", "N", "R6"]),
  Object.freeze(["B053", "Active Learning", "N", "R6"]),
  Object.freeze(["B054", "Reinforcement Learning", "N", "R8"]),
  Object.freeze(["B055", "RLHF", "N", "R8"]),
  Object.freeze(["B056", "RLAIF", "N", "R8"]),
  Object.freeze(["B057", "DPO", "N", "R8"]),
  Object.freeze(["B058", "Self-Play", "D", "R8"]),
  Object.freeze(["B059", "Curriculum Learning", "N", "R6"]),
  Object.freeze(["B060", "Meta-Learning", "N", "R8"]),
  Object.freeze(["B061", "Transfer Learning", "N", "R6"]),
  Object.freeze(["B062", "Few-Shot Learning", "P", "R4"]),
  Object.freeze(["B063", "Zero-Shot Learning", "P", "R4"]),
  Object.freeze(["B064", "Distillation", "N", "R8"]),
  Object.freeze(["B065", "Quantization", "N", "R8"]),
  Object.freeze(["B066", "Pruning", "N", "R8"]),
  Object.freeze(["B067", "LoRA", "N", "R8"]),
  Object.freeze(["B068", "Adapter Layers", "N", "R8"]),
  Object.freeze(["B069", "Mixture-of-Agents", "P", "R7"]),
  Object.freeze(["B070", "Debate System", "D", "R7"]),
  Object.freeze(["B071", "Voting Agents", "D", "R7"]),
  Object.freeze(["B072", "Judge Model", "N", "R6"]),
  Object.freeze(["B073", "Critic Model", "P", "R6"]),
  Object.freeze(["B074", "Planner-Executor", "M", "R4"]),
  Object.freeze(["B075", "Manager-Worker", "P", "R7"]),
  Object.freeze(["B076", "Specialist Agents", "P", "R7"]),
  Object.freeze(["B077", "Swarm Intelligence", "D", "R7"]),
  Object.freeze(["B078", "Blackboard Architecture", "P", "R7"]),
  Object.freeze(["B079", "Actor Model", "P", "R2"]),
  Object.freeze(["B080", "Workflow Engine", "P", "R2"]),
  Object.freeze(["B081", "State Persistence", "P", "R2"]),
  Object.freeze(["B082", "Session Manager", "P", "R1"]),
  Object.freeze(["B083", "Identity Memory", "P", "R2"]),
  Object.freeze(["B084", "Preference Learning", "P", "R6"]),
  Object.freeze(["B085", "User Modeling", "N", "R6"]),
  Object.freeze(["B086", "Intent Classification", "P", "R4"]),
  Object.freeze(["B087", "Goal Management", "P", "R4"]),
  Object.freeze(["B088", "Goal Decomposition", "P", "R4"]),
  Object.freeze(["B089", "Priority Reasoning", "P", "R4"]),
  Object.freeze(["B090", "Conflict Resolution", "P", "R4"]),
  Object.freeze(["B091", "Decision Theory", "N", "R8"]),
  Object.freeze(["B092", "Utility Engine", "P", "R6"]),
  Object.freeze(["B093", "Risk Engine", "P", "R1"]),
  Object.freeze(["B094", "Uncertainty Calibration", "N", "R6"]),
  Object.freeze(["B095", "Abstention System", "P", "R4"]),
  Object.freeze(["B096", "Fact Verification", "P", "R5"]),
  Object.freeze(["B097", "Claim Decomposition", "N", "R5"]),
  Object.freeze(["B098", "Source Reliability Model", "N", "R5"]),
  Object.freeze(["B099", "Evidence Aggregation", "P", "R5"]),
  Object.freeze(["B100", "Decision Provenance", "P", "R2"]),
]);
