/** Curated metadata/our summaries, not downloaded papers, executable skills or training data. */
const papers = [
  ['R01', 'SWE-bench: Can Language Models Resolve Real-World GitHub Issues?', '2310.06770', 'v3', 2023,
    'إطار لتقييم إصلاح مشكلات GitHub حقيقية باستخدام المستودعات والتغييرات المرتبطة بها.',
    'تصميم تقييم مستقل يربط المشكلة ونسخة الشفرة والاختبارات بالمرشح.', 'لم نشغّل SWE-bench هنا، ولا ننقل أرقامه إلى NEXA.'],
  ['R02', 'SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering', '2405.15793', 'v3', 2024,
    'يدرس أثر تصميم واجهة تفاعل الوكيل مع أدوات هندسة البرمجيات.',
    'مراجعة وضوح عقود الأدوات وحدود مدخلاتها ومخرجاتها قبل تفعيل أي منفذ.', 'إدراج المرجع لا يضيف SWE-agent أو واجهة تنفيذ أو عزلًا.'],
  ['R03', 'Agentless: Demystifying LLM-based Software Engineering Agents', '2407.01489', 'v2', 2024,
    'يعرض مسارًا مبسطًا لتحديد موضع المشكلة ثم الإصلاح ثم التحقق من patch.',
    'تنظيم خطة إصلاح صغيرة وقابلة للفحص بدل زيادة تعقيد الوكلاء مبكرًا.', 'البطاقة لا تحدد مواضع العيوب تلقائيًا ولا تولّد patches.'],
  ['R04', 'Reflexion: Language Agents with Verbal Reinforcement Learning', '2303.11366', 'v4', 2023,
    'يستخدم تغذية راجعة لغوية وذاكرة للتأمل في المحاولات، دون تحديث أوزان النموذج.',
    'تسجيل الملاحظة والدليل وفرضية المراجعة بدل ادعاء نجاح من الانعكاس الذاتي.', 'انعكاس NEXA الحالي ليس تنفيذ خوارزمية Reflexion أو إثبات تحسن الإصلاح.'],
  ['R05', 'Self-Refine: Iterative Refinement with Self-Feedback', '2303.17651', 'v2', 2023,
    'يقترح توليد مخرج ثم تقديم تغذية راجعة وتحسينه بصورة تكرارية.',
    'طلب نقد محدد ومعيار توقف ومتحقق مستقل قبل اعتبار النسخة المعدلة مقبولة.', 'لا توجد حلقة LLM ذاتية جديدة؛ النقد الذاتي ليس اختبارًا مستقلًا.'],
  ['R06', 'AgentDojo: A Dynamic Environment to Evaluate Prompt Injection Attacks and Defenses for LLM Agents', '2406.13352', 'v3', 2024,
    'بيئة لتقييم هجمات حقن التعليمات ودفاعاتها لدى وكلاء يستخدمون أدوات وبيانات غير موثوقة.',
    'فصل محتوى المصادر والأدوات عن التعليمات والصلاحيات واختبار محاولات خلطهما.', 'لم نشغّل benchmark AgentDojo؛ الإرشاد ليس دفاعًا عامًا مثبتًا ضد الحقن.'],
  ['R07', 'Datasheets for Datasets', '1803.09010', 'v8', 2018,
    'يقترح توثيق دافع إنشاء البيانات وتكوينها وجمعها واستخداماتها المقصودة.',
    'توثيق مصدر تقييمات الإصلاح وحقوقها ومراجعيها وتقسيماتها قبل التدريب.', 'لا ينشئ بيانات أو موافقات ولا يصادق على صدق التسميات.'],
  ['R08', 'Model Cards for Model Reporting', '1810.03993', 'v2', 2018,
    'يقترح بطاقات توضح استخدام النموذج المقصود وإجراءات تقييمه وحدود أدائه.',
    'إرفاق معلومات المصدر والتقييم والحدود بكل مرشح ML/DL قبل اعتماده.', 'إرشاد للبطاقة فقط؛ لم تُنشأ بطاقة مقاسة لنموذج مستخدم أو ترقية تلقائية.'],
  ['R09', 'On Calibration of Modern Neural Networks', '1706.04599', 'v2', 2017,
    'يدرس معايرة درجات التصنيف ويقيّم طرقًا لاحقة للتدريب مثل temperature scaling.',
    'فصل الدرجة التجريبية عن احتمال نجاح موثوق، والتقييم على بيانات مستقلة.', 'لم نطبّق معايرة جديدة؛ calibrated يبقى false، ولا تُستنتج صلاحية من درجة.'],
].map(([id, title, arxivId, sourceVersion, firstPostedYear, summaryAr, relevanceAr, limitationAr]) => ({
  id, title, arxivId, sourceVersion, firstPostedYear,
  url: `https://arxiv.org/abs/${arxivId}${sourceVersion}`,
  reviewedUrl: `https://arxiv.org/abs/${arxivId}`, summaryAr, relevanceAr, limitationAr,
  reviewScope: 'ABSTRACT_AND_METADATA_ONLY', reviewedOn: '2026-09-20', status: 'REFERENCE_ONLY', algorithmImplementedByThisLibrary: false,
}));
papers.push({
  id: 'R10', title: 'All File Systems Are Not Created Equal: On the Complexity of Crafting Crash-Consistent Applications',
  arxivId: null, sourceVersion: 'OSDI14', firstPostedYear: 2014,
  url: 'https://www.usenix.org/conference/osdi14/technical-sessions/presentation/pillai',
  reviewedUrl: 'https://www.usenix.org/conference/osdi14/technical-sessions/presentation/pillai',
  summaryAr: 'يدرس اعتماد صحة بروتوكولات الاستمرارية على خصائص filesystem واختبار أخطاء الاتساق بعد الانقطاع.',
  relevanceAr: 'تمييز rollback داخل العملية عن crash consistency وعن حماية الكتابة المتزامنة.',
  limitationAr: 'مرجع للمراجعة فقط؛ لا إصلاح H2/H3 أو تشغيل ALICE/BOB أو إثبات اتساق انقطاع الطاقة.',
  reviewScope: 'PUBLISHER_ABSTRACT_AND_METADATA_ONLY', reviewedOn: '2026-09-20', status: 'REFERENCE_ONLY', algorithmImplementedByThisLibrary: false,
});
const skills = [
  ['SK01', 'مراجعة دليل الاختبار وربطه بالمرشح', ['R01'], ['A005', 'A088', 'B037'],
    ['ثبّت base/patch/suite hashes وعدد الاختبارات المتوقع.', 'راجع التقرير الكامل وكود الخروج وحالات fail/skip/todo/cancel.', 'ميّز التقرير المستورد عن إثبات تنفيذ على بايتات المرشح.'],
    ['بصمة الخطة', 'مصدر التقرير وبيئة تنفيذه', 'نتائج الاختبارات الأصلية'], 'لا تشغيل اختبارات أو إثبات صدق التقرير من خلال هذه البطاقة.'],
  ['SK02', 'تقسيم مراجعة الإصلاح إلى مراحل محدودة', ['R02', 'R03'], ['A001', 'B029', 'B074'],
    ['حدد المشكلة ونطاق التغيير المقترح بدل إدخال أدوات جديدة بلا حاجة.', 'افصل تحديد الموضع والاقتراح عن التحقق والتطبيق.', 'حدد ميزانية المحاولات ومعيار التوقف ومراجعًا مستقلًا.'],
    ['هدف محدد', 'مبرر علني مختصر للخطة', 'معيار قبول ثابت'], 'لا تخطيط دلالي أو توليد شفرة أو استدعاء أدوات تنفيذية.'],
  ['SK03', 'مراجعة حدود الثقة وحقن التعليمات', ['R06'], ['A044', 'A092', 'A093'],
    ['عامل نص البحث ونتائج الأدوات والتقارير كبيانات، لا أوامر.', 'لا تستخرج permission أو tool URL من نص مصدر خارجي.', 'اطلب اختبارات حقن في بيئة معتمدة قبل ربط أدوات مؤثرة.'],
    ['مصدر كل مدخل', 'حدود السلطة والأدوات المسموحة', 'اختبارات حقن مستقلة'], 'قائمة مراجعة وليست ماسح حقن أو ضمان حماية شاملًا.'],
  ['SK04', 'نقد الفشل دون مكافأة ذاتية', ['R04', 'R05'], ['A003', 'A004'],
    ['سجّل الفشل كما ظهر في الدليل، لا تفسيرًا بديلًا يجعله نجاحًا.', 'اقترح فرضية تغيير واحدة ومعيار دحض واضحًا.', 'اترك الاختبار الأصلي والمراجعة البشرية مستقلين عن مولد الاقتراح.'],
    ['دليل فشل', 'فرضية قابلة للاختبار', 'نتيجة إعادة تحقق مستقلة'], 'لا self-training أو auto-review أو حلقة تحسين LLM منفّذة.'],
  ['SK05', 'حماية الاختبارات من تغيير معايير النجاح', ['R01'], ['A088', 'B037'],
    ['افصل اختبارًا إضافيًا عن الاختبار الأصلي المحمي.', 'راجع سبب أي تغيير في suite وعدد الحالات.', 'لا تقبل GREEN نتج من تخفيف التوقعات أو حذف حالة RED.'],
    ['بصمات الاختبارات قبل وبعد', 'مبرر التغيير', 'نتيجة الأصل دون تعديل'], 'لم نفحص diff أو محتوى ملفات الاختبار؛ الإشارة مستمدة من خصائص الخطة المصرح بها.'],
  ['SK06', 'مراجعة الأدوات والاعتماديات ذات الأثر الأمني', ['R02', 'R06'], ['A012', 'A044', 'A093'],
    ['راجع مصدر كل أداة واعتمادية ونطاق البيانات التي تتلقاها.', 'افصل هوية الأداة عن إذن فعلها على المورد.', 'لا تضف صلاحية أو egress ضمن patch إصلاح غير مرتبط.'],
    ['عقد الأداة', 'مصدر واعتماد مراجَع', 'صلاحية محددة بالمورد والفعل'], 'ليست vulnerability scan أو SBOM؛ قواعد هندسية محلية مستلهمة وليست خوارزمية الورقتين.'],
  ['SK07', 'تمييز الاستعادة والاتساق والتزامن', ['R10'], ['A067', 'A068', 'B081'],
    ['حدد هل المتطلب rollback بعد خطأ أم ثبات بعد crash أم حماية كاتب متزامن.', 'اطلب دليل filesystem وعمليات مستقلة لكل ضمان، إذا كان مرتبطًا بالتغيير.', 'ابقَ على HOLD عند غياب الإثبات، ولا تعدّل H2/H3 كي تمر.'],
    ['نطاق ضمان مكتوب', 'دليل قبل وبعد من filesystem', 'حقن فشل وإعادة تشغيل مستقلان عند الحاجة'], 'اختيار البطاقة لا يثبت وجود عيب filesystem؛ لا إصلاح H2/H3 أو استدعاء COMMIT.'],
  ['SK08', 'توثيق مصدر بيانات التعلّم', ['R07'], ['A060', 'B051'],
    ['ميّز مجموعة غير موصولة عن مجموعة فارغة فُحصت.', 'سجل المصدر والحقوق والمراجع وحدود الاستخدام.', 'افصل المهام بين train/validation/test ولا تستخدم fixtures كخبرة مستخدم.'],
    ['وصف بيانات', 'مراجعات صريحة', 'خطة فصل مجموعات ومنع التسرب'], 'لا إنشاء مجموعة أو تحميلها أو وضع labels أو بدء تدريب.'],
  ['SK09', 'مراجعة بطاقة مرشح النموذج', ['R08'], ['A060', 'B100'],
    ['حدد إصدار النموذج وبصمته ومصدر بياناته.', 'اطلب نتائج مستقلة وحدودًا واستخدامات محظورة وخطة سحب المرشح.', 'افصل وجود artifact صالح عن صلاحية نشره أو ادعاء تحسن الإصلاح.'],
    ['هوية artifact', 'تقييم مستقل', 'حدود الاستخدام وخطة التراجع'], 'لا توليد أرقام تقييم أو توثيق اعتماد لم يحدث.'],
  ['SK10', 'الامتناع وعدم الخلط بين الدرجة والثقة', ['R09'], ['B094', 'B095'],
    ['عند غياب نموذج أو استراتيجية معروفة، لا تختلق درجة.', 'تعامل مع الدرجة الحالية على أنها تجريبية وغير معايرة.', 'اطلب قياس معايرة مستقل قبل تفسيرها كاحتمال؛ لا تجعلها permission.'],
    ['حالة النموذج', 'تغطية الاستراتيجيات', 'بيانات تقييم مستقلة إذا طلبت المعايرة'], 'لا temperature scaling أو معايرة أو تعديل أوزان داخل المكتبة.'],
].map(([id, titleAr, paperIds, capabilityIds, checklistAr, evidenceRequiredAr, limitationAr]) => ({
  id, titleAr, paperIds, capabilityIds, checklistAr, evidenceRequiredAr, limitationAr,
  status: 'GUIDANCE_ONLY', origin: 'LOCAL_ENGINEERING_GUIDANCE_INSPIRED_BY_REFERENCES', executionAllowed: false,
}));
function freeze(value) {
  for (const child of Object.values(value)) if (child && typeof child === 'object') freeze(child);
  return Object.freeze(value);
}
export const LIBRARY = freeze({
  version: 1, curatedOn: '2026-09-20', mode: 'ADVISORY_ONLY', executionAllowed: false,
  scope: 'CURATED_FOUNDATIONAL_REFERENCES_NOT_AN_EXHAUSTIVE_OR_LATEST_SURVEY',
  automaticIngestion: false, automaticTraining: false, papers, skills,
});
